<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Name>Sword and Sorcery (SMAPI Component)</Name>
		<Description>C# code for Sword and Sorcery</Description>
		<UniqueId>KCC.SnS</UniqueId>
		<Authors>EnderTedi, 7thAxis, KittyCatCasey</Authors>
		<Version>2.3.9</Version>
		<TargetFramework>net6.0</TargetFramework>
		<EnableHarmony>true</EnableHarmony>
		<LangVersion>latest</LangVersion>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<TranslationClassBuilder_AddGetByKey>true</TranslationClassBuilder_AddGetByKey>
	</PropertyGroup>

	<PropertyGroup>
		<GamePath>C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley</GamePath>
		<GameModsPath>$(GamePath)\Modding</GameModsPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.1" />
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.2" />
		<PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.2.0" />
		<PackageReference Include="System.Drawing.Common" Version="4.7.2" />
	</ItemGroup>

	<ItemGroup>
		<SMAPIDependency Include="spacechase0.SpaceCore" Version="1.18.0-sdvalpha" Reference="true" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="assets\forgeButton\" />
	</ItemGroup>

</Project>